=== AnthonyTaha/alien-breed/Levels/level.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://example.com/level"
           xmlns="http://example.com/level"
           elementFormDefault="qualified">
    <xs:element name="level">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="player">
                    <xs:complexType>
                        <xs:attribute name="x" type="xs:int" use="required"/>
                        <xs:attribute name="y" type="xs:int" use="required"/>
                        <xs:attribute name="name" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="tileset" type="xs:string"/>
                <xs:element name="tileSize">
                    <xs:complexType>
                        <xs:attribute name="width" type="xs:int" use="required"/>
                        <xs:attribute name="height" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
                <xs:element name="collisionMask" type="xs:string"/>
                <xs:element name="enemies">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="enemy" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:attribute name="x" type="xs:int" use="required"/>
                                    <xs:attribute name="y" type="xs:int" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="map">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="row" type="xs:string" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="width" type="xs:int" use="required"/>
                        <xs:attribute name="height" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== AnthonyTaha/alien-breed/Levels/level.xml
<?xml version="1.0" encoding="utf-8"?>
<level xmlns="http://example.com/level"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://example.com/level level.xsd">
    <player x="5" y="2" name="player1" />
    <tileset>tileset</tileset>
    <tileSize width="16" height="16" />
    <collisionMask>1,2,3,0,7,4,6,5</collisionMask>
    <enemies>
        <enemy x="5" y="7" />
        <enemy x="5" y="17" />
    </enemies>
    <map width="10" height="21">
        <row>1,2,2,2,2,2,2,2,2,3</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>4,2,2,3,8,8,1,2,2,6</row>
        <row>8,8,8,7,8,8,0,8,8,8</row>
        <row>1,2,2,6,8,8,4,2,2,3</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>0,8,8,8,8,8,8,8,8,7</row>
        <row>4,5,5,5,5,5,5,5,5,6</row>
    </map>
</level>
